# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27229d0653020dd0814eb0ea4f2fdd80d2bb508068a07d8a42a2ac1ef06bfe6d928df33f28ecc3e2f6806d1b0a249f6318d5d522e0c34a29ad482cb8b3b247eb

test:
  secret_key_base: 93f8669dca8c4f0f4864d39ef838e203546d1d171d5e62b8d123effddcba4b1fa637bc57175cbcda3c06fdb35ef58629055921afbd5f919a5c738b4605ee12f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
